-- Fill lkp_currency table


INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (1,'AFGHANISTAN','Afghani','AFN',971);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (2,'ÅLAND ISLANDS','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (3,'ALBANIA','Lek','ALL',8);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (4,'ALGERIA','Algerian Dinar','DZD',12);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (5,'AMERICAN SAMOA','US Dollar','USD',840);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (6,'ANDORRA','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (7,'ANGOLA','Kwanza','AOA',973);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (8,'ANGUILLA','East Caribbean Dollar','XCD',951);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (9,'ANTARCTICA','No universal currency',NULL,NULL);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (10,'ANTIGUA AND BARBUDA','East Caribbean Dollar','XCD',951);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (11,'ARGENTINA','Argentine Peso','ARS',32);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (12,'ARMENIA','Armenian Dram','AMD',51);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (13,'ARUBA','Aruban Florin','AWG',533);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (14,'AUSTRALIA','Australian Dollar','AUD',36);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (15,'AUSTRIA','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (16,'AZERBAIJAN','Azerbaijan Manat','AZN',944);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (17,'BAHAMAS (THE)','Bahamian Dollar','BSD',44);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (18,'BAHRAIN','Bahraini Dinar','BHD',48);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (19,'BANGLADESH','Taka','BDT',50);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (20,'BARBADOS','Barbados Dollar','BBD',52);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (21,'BELARUS','Belarusian Ruble','BYN',933);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (22,'BELGIUM','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (23,'BELIZE','Belize Dollar','BZD',84);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (24,'BENIN','CFA Franc BCEAO','XOF',952);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (25,'BERMUDA','Bermudian Dollar','BMD',60);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (26,'BHUTAN','Indian Rupee','INR',356);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (27,'BHUTAN','Ngultrum','BTN',64);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (28,'BOLIVIA (PLURINATIONAL STATE OF)','Boliviano','BOB',68);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (29,'BOLIVIA (PLURINATIONAL STATE OF)','Mvdol','BOV',984);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (30,'BONAIRE, SINT EUSTATIUS AND SABA','US Dollar','USD',840);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (31,'BOSNIA AND HERZEGOVINA','Convertible Mark','BAM',977);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (32,'BOTSWANA','Pula','BWP',72);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (33,'BOUVET ISLAND','Norwegian Krone','NOK',578);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (34,'BRAZIL','Brazilian Real','BRL',986);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (35,'BRITISH INDIAN OCEAN TERRITORY (THE)','US Dollar','USD',840);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (36,'BRUNEI DARUSSALAM','Brunei Dollar','BND',96);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (37,'BULGARIA','Bulgarian Lev','BGN',975);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (38,'BURKINA FASO','CFA Franc BCEAO','XOF',952);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (39,'BURUNDI','Burundi Franc','BIF',108);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (40,'CABO VERDE','Cabo Verde Escudo','CVE',132);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (41,'CAMBODIA','Riel','KHR',116);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (42,'CAMEROON','CFA Franc BEAC','XAF',950);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (43,'CANADA','Canadian Dollar','CAD',124);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (44,'CAYMAN ISLANDS (THE)','Cayman Islands Dollar','KYD',136);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (45,'CENTRAL AFRICAN REPUBLIC (THE)','CFA Franc BEAC','XAF',950);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (46,'CHAD','CFA Franc BEAC','XAF',950);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (47,'CHILE','Chilean Peso','CLP',152);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (48,'CHILE','Unidad de Fomento','CLF',990);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (49,'CHINA','Yuan Renminbi','CNY',156);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (50,'CHRISTMAS ISLAND','Australian Dollar','AUD',36);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (51,'COCOS (KEELING) ISLANDS (THE)','Australian Dollar','AUD',36);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (52,'COLOMBIA','Colombian Peso','COP',170);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (53,'COLOMBIA','Unidad de Valor Real','COU',970);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (54,'COMOROS (THE)','Comorian Franc','KMF',174);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (55,'CONGO (THE DEMOCRATIC REPUBLIC OF THE)','Congolese Franc','CDF',976);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (56,'CONGO (THE)','CFA Franc BEAC','XAF',950);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (57,'COOK ISLANDS (THE)','New Zealand Dollar','NZD',554);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (58,'COSTA RICA','Costa Rican Colon','CRC',188);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (59,'CÔTE D''IVOIRE','CFA Franc BCEAO','XOF',952);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (60,'CROATIA','Kuna','HRK',191);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (61,'CUBA','Cuban Peso','CUP',192);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (62,'CUBA','Peso Convertible','CUC',931);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (63,'CURAÇAO','Netherlands Antillean Guilder','ANG',532);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (64,'CYPRUS','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (65,'CZECHIA','Czech Koruna','CZK',203);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (66,'DENMARK','Danish Krone','DKK',208);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (67,'DJIBOUTI','Djibouti Franc','DJF',262);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (68,'DOMINICA','East Caribbean Dollar','XCD',951);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (69,'DOMINICAN REPUBLIC (THE)','Dominican Peso','DOP',214);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (70,'ECUADOR','US Dollar','USD',840);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (71,'EGYPT','Egyptian Pound','EGP',818);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (72,'EL SALVADOR','El Salvador Colon','SVC',222);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (73,'EL SALVADOR','US Dollar','USD',840);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (74,'EQUATORIAL GUINEA','CFA Franc BEAC','XAF',950);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (75,'ERITREA','Nakfa','ERN',232);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (76,'ESTONIA','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (77,'ESWATINI','Lilangeni','SZL',748);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (78,'ETHIOPIA','Ethiopian Birr','ETB',230);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (79,'EUROPEAN UNION','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (80,'FALKLAND ISLANDS (THE) [MALVINAS]','Falkland Islands Pound','FKP',238);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (81,'FAROE ISLANDS (THE)','Danish Krone','DKK',208);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (82,'FIJI','Fiji Dollar','FJD',242);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (83,'FINLAND','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (84,'FRANCE','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (85,'FRENCH GUIANA','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (86,'FRENCH POLYNESIA','CFP Franc','XPF',953);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (87,'FRENCH SOUTHERN TERRITORIES (THE)','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (88,'GABON','CFA Franc BEAC','XAF',950);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (89,'GAMBIA (THE)','Dalasi','GMD',270);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (90,'GEORGIA','Lari','GEL',981);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (91,'GERMANY','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (92,'GHANA','Ghana Cedi','GHS',936);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (93,'GIBRALTAR','Gibraltar Pound','GIP',292);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (94,'GREECE','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (95,'GREENLAND','Danish Krone','DKK',208);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (96,'GRENADA','East Caribbean Dollar','XCD',951);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (97,'GUADELOUPE','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (98,'GUAM','US Dollar','USD',840);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (99,'GUATEMALA','Quetzal','GTQ',320);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (100,'GUERNSEY','Pound Sterling','GBP',826);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (101,'GUINEA','Guinean Franc','GNF',324);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (102,'GUINEA-BISSAU','CFA Franc BCEAO','XOF',952);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (103,'GUYANA','Guyana Dollar','GYD',328);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (104,'HAITI','Gourde','HTG',332);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (105,'HAITI','US Dollar','USD',840);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (106,'HEARD ISLAND AND McDONALD ISLANDS','Australian Dollar','AUD',36);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (107,'HOLY SEE (THE)','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (108,'HONDURAS','Lempira','HNL',340);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (109,'HONG KONG','Hong Kong Dollar','HKD',344);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (110,'HUNGARY','Forint','HUF',348);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (111,'ICELAND','Iceland Krona','ISK',352);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (112,'INDIA','Indian Rupee','INR',356);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (113,'INDONESIA','Rupiah','IDR',360);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (114,'INTERNATIONAL MONETARY FUND (IMF)','SDR (Special Drawing Right)','XDR',960);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (115,'IRAN (ISLAMIC REPUBLIC OF)','Iranian Rial','IRR',364);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (116,'IRAQ','Iraqi Dinar','IQD',368);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (117,'IRELAND','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (118,'ISLE OF MAN','Pound Sterling','GBP',826);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (119,'ISRAEL','New Israeli Sheqel','ILS',376);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (120,'ITALY','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (121,'JAMAICA','Jamaican Dollar','JMD',388);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (122,'JAPAN','Yen','JPY',392);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (123,'JERSEY','Pound Sterling','GBP',826);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (124,'JORDAN','Jordanian Dinar','JOD',400);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (125,'KAZAKHSTAN','Tenge','KZT',398);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (126,'KENYA','Kenyan Shilling','KES',404);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (127,'KIRIBATI','Australian Dollar','AUD',36);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (128,'KOREA (THE DEMOCRATIC PEOPLE''S REPUBLIC OF)','North Korean Won','KPW',408);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (129,'KOREA (THE REPUBLIC OF)','Won','KRW',410);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (130,'KUWAIT','Kuwaiti Dinar','KWD',414);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (131,'KYRGYZSTAN','Som','KGS',417);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (132,'LAO PEOPLE''S DEMOCRATIC REPUBLIC (THE)','Lao Kip','LAK',418);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (133,'LATVIA','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (134,'LEBANON','Lebanese Pound','LBP',422);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (135,'LESOTHO','Loti','LSL',426);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (136,'LESOTHO','Rand','ZAR',710);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (137,'LIBERIA','Liberian Dollar','LRD',430);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (138,'LIBYA','Libyan Dinar','LYD',434);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (139,'LIECHTENSTEIN','Swiss Franc','CHF',756);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (140,'LITHUANIA','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (141,'LUXEMBOURG','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (142,'MACAO','Pataca','MOP',446);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (143,'NORTH MACEDONIA','Denar','MKD',807);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (144,'MADAGASCAR','Malagasy Ariary','MGA',969);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (145,'MALAWI','Malawi Kwacha','MWK',454);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (146,'MALAYSIA','Malaysian Ringgit','MYR',458);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (147,'MALDIVES','Rufiyaa','MVR',462);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (148,'MALI','CFA Franc BCEAO','XOF',952);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (149,'MALTA','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (150,'MARSHALL ISLANDS (THE)','US Dollar','USD',840);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (151,'MARTINIQUE','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (152,'MAURITANIA','Ouguiya','MRU',929);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (153,'MAURITIUS','Mauritius Rupee','MUR',480);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (154,'MAYOTTE','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (155,'MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP','ADB Unit of Account','XUA',965);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (156,'MEXICO','Mexican Peso','MXN',484);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (157,'MEXICO','Mexican Unidad de Inversion (UDI)','MXV',979);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (158,'MICRONESIA (FEDERATED STATES OF)','US Dollar','USD',840);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (159,'MOLDOVA (THE REPUBLIC OF)','Moldovan Leu','MDL',498);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (160,'MONACO','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (161,'MONGOLIA','Tugrik','MNT',496);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (162,'MONTENEGRO','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (163,'MONTSERRAT','East Caribbean Dollar','XCD',951);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (164,'MOROCCO','Moroccan Dirham','MAD',504);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (165,'MOZAMBIQUE','Mozambique Metical','MZN',943);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (166,'MYANMAR','Kyat','MMK',104);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (167,'NAMIBIA','Namibia Dollar','NAD',516);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (168,'NAMIBIA','Rand','ZAR',710);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (169,'NAURU','Australian Dollar','AUD',36);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (170,'NEPAL','Nepalese Rupee','NPR',524);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (171,'NETHERLANDS (THE)','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (172,'NEW CALEDONIA','CFP Franc','XPF',953);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (173,'NEW ZEALAND','New Zealand Dollar','NZD',554);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (174,'NICARAGUA','Cordoba Oro','NIO',558);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (175,'NIGER (THE)','CFA Franc BCEAO','XOF',952);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (176,'NIGERIA','Naira','NGN',566);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (177,'NIUE','New Zealand Dollar','NZD',554);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (178,'NORFOLK ISLAND','Australian Dollar','AUD',36);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (179,'NORTHERN MARIANA ISLANDS (THE)','US Dollar','USD',840);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (180,'NORWAY','Norwegian Krone','NOK',578);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (181,'OMAN','Rial Omani','OMR',512);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (182,'PAKISTAN','Pakistan Rupee','PKR',586);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (183,'PALAU','US Dollar','USD',840);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (184,'PALESTINE, STATE OF','No universal currency',NULL,NULL);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (185,'PANAMA','Balboa','PAB',590);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (186,'PANAMA','US Dollar','USD',840);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (187,'PAPUA NEW GUINEA','Kina','PGK',598);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (188,'PARAGUAY','Guarani','PYG',600);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (189,'PERU','Sol','PEN',604);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (190,'PHILIPPINES (THE)','Philippine Peso','PHP',608);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (191,'PITCAIRN','New Zealand Dollar','NZD',554);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (192,'POLAND','Zloty','PLN',985);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (193,'PORTUGAL','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (194,'PUERTO RICO','US Dollar','USD',840);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (195,'QATAR','Qatari Rial','QAR',634);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (196,'RÉUNION','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (197,'ROMANIA','Romanian Leu','RON',946);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (198,'RUSSIAN FEDERATION (THE)','Russian Ruble','RUB',643);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (199,'RWANDA','Rwanda Franc','RWF',646);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (200,'SAINT BARTHÉLEMY','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (201,'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA','Saint Helena Pound','SHP',654);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (202,'SAINT KITTS AND NEVIS','East Caribbean Dollar','XCD',951);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (203,'SAINT LUCIA','East Caribbean Dollar','XCD',951);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (204,'SAINT MARTIN (FRENCH PART)','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (205,'SAINT PIERRE AND MIQUELON','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (206,'SAINT VINCENT AND THE GRENADINES','East Caribbean Dollar','XCD',951);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (207,'SAMOA','Tala','WST',882);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (208,'SAN MARINO','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (209,'SAO TOME AND PRINCIPE','Dobra','STN',930);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (210,'SAUDI ARABIA','Saudi Riyal','SAR',682);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (211,'SENEGAL','CFA Franc BCEAO','XOF',952);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (212,'SERBIA','Serbian Dinar','RSD',941);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (213,'SEYCHELLES','Seychelles Rupee','SCR',690);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (214,'SIERRA LEONE','Leone','SLL',694);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (215,'SINGAPORE','Singapore Dollar','SGD',702);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (216,'SINT MAARTEN (DUTCH PART)','Netherlands Antillean Guilder','ANG',532);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (217,'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"','Sucre','XSU',994);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (218,'SLOVAKIA','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (219,'SLOVENIA','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (220,'SOLOMON ISLANDS','Solomon Islands Dollar','SBD',90);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (221,'SOMALIA','Somali Shilling','SOS',706);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (222,'SOUTH AFRICA','Rand','ZAR',710);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (223,'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','No universal currency',NULL,NULL);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (224,'SOUTH SUDAN','South Sudanese Pound','SSP',728);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (225,'SPAIN','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (226,'SRI LANKA','Sri Lanka Rupee','LKR',144);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (227,'SUDAN (THE)','Sudanese Pound','SDG',938);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (228,'SURINAME','Surinam Dollar','SRD',968);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (229,'SVALBARD AND JAN MAYEN','Norwegian Krone','NOK',578);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (230,'SWEDEN','Swedish Krona','SEK',752);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (231,'SWITZERLAND','Swiss Franc','CHF',756);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (232,'SWITZERLAND','WIR Euro','CHE',947);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (233,'SWITZERLAND','WIR Franc','CHW',948);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (234,'SYRIAN ARAB REPUBLIC','Syrian Pound','SYP',760);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (235,'TAIWAN (PROVINCE OF CHINA)','New Taiwan Dollar','TWD',901);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (236,'TAJIKISTAN','Somoni','TJS',972);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (237,'TANZANIA, UNITED REPUBLIC OF','Tanzanian Shilling','TZS',834);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (238,'THAILAND','Baht','THB',764);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (239,'TIMOR-LESTE','US Dollar','USD',840);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (240,'TOGO','CFA Franc BCEAO','XOF',952);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (241,'TOKELAU','New Zealand Dollar','NZD',554);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (242,'TONGA','Pa''anga','TOP',776);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (243,'TRINIDAD AND TOBAGO','Trinidad and Tobago Dollar','TTD',780);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (244,'TUNISIA','Tunisian Dinar','TND',788);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (245,'TURKEY','Turkish Lira','TRY',949);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (246,'TURKMENISTAN','Turkmenistan New Manat','TMT',934);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (247,'TURKS AND CAICOS ISLANDS (THE)','US Dollar','USD',840);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (248,'TUVALU','Australian Dollar','AUD',36);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (249,'UGANDA','Uganda Shilling','UGX',800);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (250,'UKRAINE','Hryvnia','UAH',980);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (251,'UNITED ARAB EMIRATES (THE)','UAE Dirham','AED',784);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (252,'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)','Pound Sterling','GBP',826);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (253,'UNITED STATES MINOR OUTLYING ISLANDS (THE)','US Dollar','USD',840);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (254,'UNITED STATES OF AMERICA (THE)','US Dollar','USD',840);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (255,'UNITED STATES OF AMERICA (THE)','US Dollar (Next day)','USN',997);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (256,'URUGUAY','Peso Uruguayo','UYU',858);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (257,'URUGUAY','Uruguay Peso en Unidades Indexadas (UI)','UYI',940);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (258,'URUGUAY','Unidad Previsional','UYW',927);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (259,'UZBEKISTAN','Uzbekistan Sum','UZS',860);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (260,'VANUATU','Vatu','VUV',548);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (261,'VENEZUELA (BOLIVARIAN REPUBLIC OF)','Bolívar Soberano','VES',928);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (262,'VIET NAM','Dong','VND',704);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (263,'VIRGIN ISLANDS (BRITISH)','US Dollar','USD',840);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (264,'VIRGIN ISLANDS (U.S.)','US Dollar','USD',840);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (265,'WALLIS AND FUTUNA','CFP Franc','XPF',953);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (266,'WESTERN SAHARA','Moroccan Dirham','MAD',504);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (267,'YEMEN','Yemeni Rial','YER',886);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (268,'ZAMBIA','Zambian Kwacha','ZMW',967);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (269,'ZIMBABWE','Zimbabwe Dollar','ZWL',932);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (270,'ZZ01_Bond Markets Unit European_EURCO','Bond Markets Unit European Composite Unit (EURCO)','XBA',955);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (271,'ZZ02_Bond Markets Unit European_EMU-6','Bond Markets Unit European Monetary Unit (E.M.U.-6)','XBB',956);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (272,'ZZ03_Bond Markets Unit European_EUA-9','Bond Markets Unit European Unit of Account 9 (E.U.A.-9)','XBC',957);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (273,'ZZ04_Bond Markets Unit European_EUA-17','Bond Markets Unit European Unit of Account 17 (E.U.A.-17)','XBD',958);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (274,'ZZ06_Testing_Code','Codes specifically reserved for testing purposes','XTS',963);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (275,'ZZ07_No_Currency','The codes assigned for transactions where no currency is involved','XXX',999);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (276,'ZZ08_Gold','Gold','XAU',959);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (277,'ZZ09_Palladium','Palladium','XPD',964);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (278,'ZZ10_Platinum','Platinum','XPT',962);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (279,'ZZ11_Silver','Silver','XAG',961);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (280,'AFGHANISTAN','Afghani','AFA',4);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (281,'ÅLAND ISLANDS','Markka','FIM',246);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (282,'ALBANIA','Old Lek','ALK',8);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (283,'ANDORRA','Andorran Peseta','ADP',20);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (284,'ANDORRA','Spanish Peseta','ESP',724);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (285,'ANDORRA','French Franc','FRF',250);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (286,'ANGOLA','Kwanza','AOK',24);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (287,'ANGOLA','New Kwanza','AON',24);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (288,'ANGOLA','Kwanza Reajustado','AOR',982);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (289,'ARGENTINA','Austral','ARA',32);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (290,'ARGENTINA','Peso Argentino','ARP',32);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (291,'ARGENTINA','Peso','ARY',32);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (292,'ARMENIA','Russian Ruble','RUR',810);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (293,'AUSTRIA','Schilling','ATS',40);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (294,'AZERBAIJAN','Azerbaijan Manat','AYM',945);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (295,'AZERBAIJAN','Azerbaijanian Manat','AZM',31);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (296,'AZERBAIJAN','Russian Ruble','RUR',810);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (297,'BELARUS','Belarusian Ruble','BYB',112);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (298,'BELARUS','Belarusian Ruble','BYR',974);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (299,'BELARUS','Russian Ruble','RUR',810);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (300,'BELGIUM','Convertible Franc','BEC',993);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (301,'BELGIUM','Belgian Franc','BEF',56);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (302,'BELGIUM','Financial Franc','BEL',992);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (303,'BOLIVIA','Peso boliviano','BOP',68);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (304,'BOSNIA AND HERZEGOVINA','Dinar','BAD',70);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (305,'BRAZIL','Cruzeiro','BRB',76);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (306,'BRAZIL','Cruzado','BRC',76);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (307,'BRAZIL','Cruzeiro','BRE',76);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (308,'BRAZIL','New Cruzado','BRN',76);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (309,'BRAZIL','Cruzeiro Real','BRR',987);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (310,'BULGARIA','Lev A/52','BGJ',100);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (311,'BULGARIA','Lev A/62','BGK',100);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (312,'BULGARIA','Lev','BGL',100);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (313,'BURMA','Kyat','BUK',104);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (314,'CROATIA','Croatian Dinar','HRD',191);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (315,'CROATIA','Croatian Kuna','HRK',191);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (316,'CYPRUS','Cyprus Pound','CYP',196);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (317,'CZECHOSLOVAKIA','Krona A/53','CSJ',203);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (318,'CZECHOSLOVAKIA','Koruna','CSK',200);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (319,'ECUADOR','Sucre','ECS',218);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (320,'ECUADOR','Unidad de Valor Constante (UVC)','ECV',983);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (321,'EQUATORIAL GUINEA','Ekwele','GQE',226);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (322,'ESTONIA','Kroon','EEK',233);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (323,'EUROPEAN MONETARY CO-OPERATION FUND (EMCF)','European Currency Unit (E.C.U)','XEU',954);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (324,'FINLAND','Markka','FIM',246);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (325,'FRANCE','French Franc','FRF',250);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (326,'FRENCH GUIANA','French Franc','FRF',250);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (327,'FRENCH SOUTHERN TERRITORIES','French Franc','FRF',250);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (328,'GEORGIA','Georgian Coupon','GEK',268);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (329,'GEORGIA','Russian Ruble','RUR',810);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (330,'GERMAN DEMOCRATIC REPUBLIC','Mark der DDR','DDM',278);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (331,'GERMANY','Deutsche Mark','DEM',276);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (332,'GHANA','Cedi','GHC',288);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (333,'GHANA','Ghana Cedi','GHP',939);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (334,'GREECE','Drachma','GRD',300);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (335,'GUADELOUPE','French Franc','FRF',250);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (336,'GUINEA','Syli','GNE',324);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (337,'GUINEA','Syli','GNS',324);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (338,'GUINEA-BISSAU','Guinea Escudo','GWE',624);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (339,'GUINEA-BISSAU','Guinea-Bissau Peso','GWP',624);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (340,'HOLY SEE (VATICAN CITY STATE)','Italian Lira','ITL',380);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (341,'ICELAND','Old Krona','ISJ',352);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (342,'IRELAND','Irish Pound','IEP',372);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (343,'ISRAEL','Pound','ILP',376);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (344,'ISRAEL','Old Shekel','ILR',376);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (345,'ITALY','Italian Lira','ITL',380);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (346,'KAZAKHSTAN','Russian Ruble','RUR',810);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (347,'KYRGYZSTAN','Russian Ruble','RUR',810);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (348,'LAO','Pathet Lao Kip','LAJ',418);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (349,'LATVIA','Latvian Lats','LVL',428);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (350,'LATVIA','Latvian Ruble','LVR',428);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (351,'LESOTHO','Loti','LSM',426);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (352,'LESOTHO','Financial Rand','ZAL',991);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (353,'LITHUANIA','Lithuanian Litas','LTL',440);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (354,'LITHUANIA','Talonas','LTT',440);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (355,'LUXEMBOURG','Luxembourg Convertible Franc','LUC',989);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (356,'LUXEMBOURG','Luxembourg Franc','LUF',442);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (357,'LUXEMBOURG','Luxembourg Financial Franc','LUL',988);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (358,'MADAGASCAR','Malagasy Franc','MGF',450);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (359,'MALAWI','Kwacha','MWK',454);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (360,'MALDIVES','Maldive Rupee','MVQ',462);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (361,'MALI','Mali Franc','MLF',466);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (362,'MALTA','Maltese Lira','MTL',470);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (363,'MALTA','Maltese Pound','MTP',470);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (364,'MARTINIQUE','French Franc','FRF',250);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (365,'MAURITANIA','Ouguiya','MRO',478);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (366,'MAYOTTE','French Franc','FRF',250);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (367,'MEXICO','Mexican Peso','MXP',484);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (368,'MOLDOVA, REPUBLIC OF','Russian Ruble','RUR',810);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (369,'MONACO','French Franc','FRF',250);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (370,'MOZAMBIQUE','Mozambique Escudo','MZE',508);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (371,'MOZAMBIQUE','Mozambique Metical','MZM',508);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (372,'NETHERLANDS','Netherlands Guilder','NLG',528);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (373,'NETHERLANDS ANTILLES','Netherlands Antillean Guilder','ANG',532);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (374,'NICARAGUA','Cordoba','NIC',558);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (375,'PERU','Sol','PEH',604);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (376,'PERU','Inti','PEI',604);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (377,'PERU','Nuevo Sol','PEN',604);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (378,'PERU','Sol','PES',604);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (379,'POLAND','Zloty','PLZ',616);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (380,'PORTUGAL','Portuguese Escudo','PTE',620);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (381,'RÉUNION','French Franc','FRF',250);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (382,'ROMANIA','Leu A/52','ROK',642);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (383,'ROMANIA','Old Leu','ROL',642);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (384,'ROMANIA','New Romanian Leu','RON',946);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (385,'RUSSIAN FEDERATION','Russian Ruble','RUR',810);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (386,'SAINT MARTIN','French Franc','FRF',250);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (387,'SAINT PIERRE AND MIQUELON','French Franc','FRF',250);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (388,'SAINT-BARTHÉLEMY','French Franc','FRF',250);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (389,'SAN MARINO','Italian Lira','ITL',380);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (390,'SAO TOME AND PRINCIPE','Dobra','STD',678);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (391,'SERBIA AND MONTENEGRO','Serbian Dinar','CSD',891);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (392,'SERBIA AND MONTENEGRO','Euro','EUR',978);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (393,'SLOVAKIA','Slovak Koruna','SKK',703);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (394,'SLOVENIA','Tolar','SIT',705);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (395,'SOUTH AFRICA','Financial Rand','ZAL',991);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (396,'SOUTH SUDAN','Sudanese Pound','SDG',938);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (397,'SOUTHERN RHODESIA','Rhodesian Dollar','RHD',716);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (398,'SPAIN','Spanish Peseta','ESA',996);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (399,'SPAIN','"A" Account (convertible Peseta Account)','ESB',995);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (400,'SPAIN','Spanish Peseta','ESP',724);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (401,'SUDAN','Sudanese Dinar','SDD',736);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (402,'SUDAN','Sudanese Pound','SDP',736);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (403,'SURINAME','Surinam Guilder','SRG',740);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (404,'SWAZILAND','Lilangeni','SZL',748);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (405,'SWITZERLAND','WIR Franc (for electronic)','CHC',948);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (406,'TAJIKISTAN','Russian Ruble','RUR',810);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (407,'TAJIKISTAN','Tajik Ruble','TJR',762);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (408,'TIMOR-LESTE','Rupiah','IDR',360);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (409,'TIMOR-LESTE','Timor Escudo','TPE',626);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (410,'TURKEY','Old Turkish Lira','TRL',792);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (411,'TURKEY','New Turkish Lira','TRY',949);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (412,'TURKMENISTAN','Russian Ruble','RUR',810);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (413,'TURKMENISTAN','Turkmenistan Manat','TMM',795);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (414,'UGANDA','Uganda Shilling','UGS',800);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (415,'UGANDA','Old Shilling','UGW',800);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (416,'UKRAINE','Karbovanet','UAK',804);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (417,'UNION OF SOVIET SOCIALIST REPUBLICS','Rouble','SUR',810);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (418,'UNITED STATES','US Dollar (Same day)','USS',998);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (419,'URUGUAY','Old Uruguay Peso','UYN',858);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (420,'URUGUAY','Uruguayan Peso','UYP',858);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (421,'UZBEKISTAN','Russian Ruble','RUR',810);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (422,'VENEZUELA','Bolivar','VEB',862);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (423,'VENEZUELA','Bolivar Fuerte','VEF',937);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (424,'VENEZUELA (BOLIVARIAN REPUBLIC OF)','Bolivar','VEF',937);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (425,'VENEZUELA (BOLIVARIAN REPUBLIC OF)','Bolívar','VEF',937);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (426,'VIETNAM','Old Dong','VNC',704);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (427,'YEMEN, DEMOCRATIC','Yemeni Dinar','YDD',720);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (428,'YUGOSLAVIA','New Yugoslavian Dinar','YUD',890);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (429,'YUGOSLAVIA','New Dinar','YUM',891);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (430,'YUGOSLAVIA','Yugoslavian Dinar','YUN',890);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (431,'ZAIRE','New Zaire','ZRN',180);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (432,'ZAIRE','Zaire','ZRZ',180);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (433,'ZAMBIA','Zambian Kwacha','ZMK',894);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (434,'ZIMBABWE','Rhodesian Dollar','ZWC',716);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (435,'ZIMBABWE','Zimbabwe Dollar (old)','ZWD',716);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (436,'ZIMBABWE','Zimbabwe Dollar','ZWD',716);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (437,'ZIMBABWE','Zimbabwe Dollar (new)','ZWN',942);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (438,'ZIMBABWE','Zimbabwe Dollar','ZWR',935);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (439,'ZZ01_Gold-Franc','Gold-Franc','XFO',NULL);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (440,'ZZ02_RINET Funds Code','RINET Funds Code','XRE',NULL);
INSERT INTO lkp_currency(id,country,currency,alphabetic_code,numeric_code) VALUES (441,'ZZ05_UIC-Franc','UIC-Franc','XFU',NULL);
